# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "say_goodbye": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["nbdev_sample.py"]

doc_url = "https://striderw.github.io/nbdev_sample/"

git_url = "https://github.com/striderw/nbdev_sample/tree/master/"

def custom_doc_links(name): return None
