# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_goodbye', 'HelloSayer']

# Cell
def say_hello(to):
    "Say Hello to Somebody"
    return f'Hello {to}!'

# Cell
def say_goodbye(c):
    "Say goodbye to Somebody"
    return f"Goodbye {c}!"

# Cell
class HelloSayer:
    "Say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to

    def say(self):
        "Do the saying"
        print(say_hello(self.to))