# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_goodbye']

# Cell
def say_hello(to):
    "Say Hello to Somebody"
    return f'Hello {to}!'

# Cell
def say_goodbye(c):
    "Say goodbye to Somebody"
    return f"Goodbye {c}!"